// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmQeY0cKO208_mWFg1MVYRQZv8_1wBKV8',
    appId: '1:622802398669:web:afd4f29a3e44b0fe29a884',
    messagingSenderId: '622802398669',
    projectId: 'todo-79165',
    authDomain: 'todo-79165.firebaseapp.com',
    storageBucket: 'todo-79165.appspot.com',
    measurementId: 'G-RMZDBYB9FS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBillFlwpgqVB3rWnnbszHE8tB7H1U0WdM',
    appId: '1:622802398669:android:934d3555fd323c9229a884',
    messagingSenderId: '622802398669',
    projectId: 'todo-79165',
    storageBucket: 'todo-79165.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoHsrCo1tlhzU8Uvwfo9e0MwRbducAnqY',
    appId: '1:622802398669:ios:24907b6ccdc672b829a884',
    messagingSenderId: '622802398669',
    projectId: 'todo-79165',
    storageBucket: 'todo-79165.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoHsrCo1tlhzU8Uvwfo9e0MwRbducAnqY',
    appId: '1:622802398669:ios:002e132b12c7420f29a884',
    messagingSenderId: '622802398669',
    projectId: 'todo-79165',
    storageBucket: 'todo-79165.appspot.com',
    iosBundleId: 'com.example.untitled1.RunnerTests',
  );
}
